import { Body, Controller, Get, Param, Post } from '@nestjs/common';
import { z } from 'zod';
import { CurrentActor } from '../../common/auth/current-actor.decorator'; import type { Actor } from '../../common/auth/auth.types'; import { Roles } from '../../common/auth/roles.decorator'; import { CurrentTenant } from '../../common/tenant/current-tenant.decorator'; import { TenantDbService } from '../../common/tenant/tenant-db.service'; import { PrismaService } from '../../prisma/prisma.service'; import { AuditService } from '../audit/audit.service';
const Schema=z.object({serviceProviderId:z.string().uuid(),evidenceId:z.string().uuid(),scope:z.record(z.string(),z.any()),validFrom:z.string().datetime().optional(),validUntil:z.string().datetime().optional()});
@Controller('authorisations')
export class AuthorisationsController {constructor(private readonly tenantDb:TenantDbService,private readonly prisma:PrismaService,private readonly audit:AuditService){}
 @Get() list(@CurrentTenant() orgId:string){return this.prisma.writtenAuthorisation.findMany({where:{responsibleOperatorId:orgId},include:{serviceProvider:true},orderBy:{createdAt:'desc'}});}
 @Post() @Roles('operator_admin') async create(@CurrentTenant() orgId:string,@CurrentActor() actor:Actor,@Body() body:unknown){const b=Schema.parse(body);const evidence=await this.tenantDb.run(orgId,tx=>tx.evidenceObject.findFirstOrThrow({where:{id:b.evidenceId,organisationId:orgId}}));const row=await this.prisma.writtenAuthorisation.create({data:{responsibleOperatorId:orgId,serviceProviderId:b.serviceProviderId,scopeJson:b.scope,documentObjectKey:evidence.objectKey,documentSha256:evidence.sha256||'',validFrom:b.validFrom?new Date(b.validFrom):new Date(),validUntil:b.validUntil?new Date(b.validUntil):undefined}});await this.audit.log({organisationId:orgId,actorSubject:actor.subject,action:'authorisation.create',resourceType:'written_authorisation',resourceId:row.id,metadata:{serviceProviderId:b.serviceProviderId}});return row;}
 @Post(':id/revoke') @Roles('operator_admin') async revoke(@CurrentTenant() orgId:string,@CurrentActor() actor:Actor,@Param('id') id:string){const existing=await this.prisma.writtenAuthorisation.findFirstOrThrow({where:{id,responsibleOperatorId:orgId}});const row=await this.prisma.writtenAuthorisation.update({where:{id},data:{revokedAt:new Date()}});await this.audit.log({organisationId:orgId,actorSubject:actor.subject,action:'authorisation.revoke',resourceType:'written_authorisation',resourceId:id,metadata:{serviceProviderId:existing.serviceProviderId}});return row;}
}
