import { Body, ConflictException, Controller, Get, Param, Post } from '@nestjs/common';
import { z } from 'zod';
import { CurrentActor } from '../../common/auth/current-actor.decorator'; import type { Actor } from '../../common/auth/auth.types'; import { CurrentTenant } from '../../common/tenant/current-tenant.decorator'; import { TenantDbService } from '../../common/tenant/tenant-db.service'; import { hashJson } from '../../common/crypto/canonical'; import { AuditService } from '../audit/audit.service';
const EventSchema=z.object({eventType:z.enum(['status_change','repair','accident','repurpose','reuse','remanufacture','recycle']),eventTime:z.string().datetime(),payload:z.record(z.string(),z.any()).default({}),previousPassportId:z.string().uuid().optional(),newLifecycleStatus:z.enum(['original','repurposed','reused','remanufactured','waste','recycled']).optional()});
const TelemetrySchema=z.object({readings:z.array(z.object({measuredAt:z.string().datetime(),metric:z.string().min(1).max(100),value:z.number().optional(),unit:z.string().max(40).optional(),payload:z.any().optional(),source:z.string().max(200).optional()})).min(1).max(1000)});
@Controller('lifecycle')
export class LifecycleController {constructor(private readonly tenantDb:TenantDbService,private readonly audit:AuditService){}
 @Get(':itemId/events') events(@CurrentTenant() orgId:string,@Param('itemId') itemId:string){return this.tenantDb.run(orgId,tx=>tx.lifecycleEvent.findMany({where:{organisationId:orgId,batteryItemId:itemId},orderBy:{eventTime:'desc'}}));}
 @Post(':itemId/events') async event(@CurrentTenant() orgId:string,@CurrentActor() actor:Actor,@Param('itemId') itemId:string,@Body() body:unknown){const b=EventSchema.parse(body);if(['repurpose','reuse','remanufacture'].includes(b.eventType)&&!b.previousPassportId)throw new ConflictException({code:'PRIOR_PASSPORT_REQUIRED',message:'Repurpose/reuse/remanufacture events must link to the prior passport.'});const integrityHash=hashJson({itemId,...b});const row=await this.tenantDb.run(orgId,async tx=>{const item=await tx.batteryItem.findFirstOrThrow({where:{id:itemId,organisationId:orgId}});const ev=await tx.lifecycleEvent.create({data:{organisationId:orgId,batteryItemId:itemId,eventType:b.eventType,eventTime:new Date(b.eventTime),payload:b.payload,previousPassportId:b.previousPassportId,integrityHash}});if(b.newLifecycleStatus||b.eventType==='recycle')await tx.batteryItem.update({where:{id:item.id},data:{lifecycleStatus:b.eventType==='recycle'?'recycled':b.newLifecycleStatus,passportState:b.eventType==='recycle'?'recycled':'updated'}});return ev;});await this.audit.log({organisationId:orgId,actorSubject:actor.subject,action:'lifecycle.event',resourceType:'battery_item',resourceId:itemId,metadata:{eventType:b.eventType}});return row;}
 @Post(':itemId/telemetry') async telemetry(@CurrentTenant() orgId:string,@CurrentActor() actor:Actor,@Param('itemId') itemId:string,@Body() body:unknown){const b=TelemetrySchema.parse(body);const count=await this.tenantDb.run(orgId,async tx=>{await tx.batteryItem.findFirstOrThrow({where:{id:itemId,organisationId:orgId}});for(const r of b.readings){const integrityHash=hashJson({itemId,...r});await tx.telemetryReading.create({data:{organisationId:orgId,batteryItemId:itemId,measuredAt:new Date(r.measuredAt),metric:r.metric,value:r.value,unit:r.unit,payload:r.payload,source:r.source,integrityHash}});}await tx.batteryItem.updateMany({where:{id:itemId,organisationId:orgId,passportState:{in:['published','registered','registry_pending']}},data:{passportState:'updated'}});return b.readings.length;});await this.audit.log({organisationId:orgId,actorSubject:actor.subject,action:'telemetry.ingest',resourceType:'battery_item',resourceId:itemId,metadata:{count}});return {accepted:count};}
}
