import { Body, ConflictException, Controller, Headers, Post } from '@nestjs/common';
import { ConfigService } from '@nestjs/config'; import { z } from 'zod'; import { fields } from '@eubp/rules';
import { CurrentActor } from '../../common/auth/current-actor.decorator'; import type { Actor } from '../../common/auth/auth.types'; import { Public } from '../../common/auth/public.decorator'; import { CurrentTenant } from '../../common/tenant/current-tenant.decorator'; import { TenantDbService } from '../../common/tenant/tenant-db.service'; import { secureToken,sha256Hex } from '../../common/crypto/canonical'; import { AuditService } from '../audit/audit.service'; import { AccessTokenService } from './access-token.service';
const GrantSchema=z.object({batteryItemId:z.string().uuid(),granteeSubject:z.string().min(1),granteeRole:z.string().min(1),accessTier:z.enum(['legitimate_interest_model','legitimate_interest_item']),purpose:z.string().min(3).max(1000),validForHours:z.number().int().min(1).max(24*90).default(24)});
@Controller()
export class AccessController {constructor(private readonly tenantDb:TenantDbService,private readonly config:ConfigService,private readonly audit:AuditService,private readonly tokens:AccessTokenService){}
 @Post('access-grants') async create(@CurrentTenant() orgId:string,@CurrentActor() actor:Actor,@Body() body:unknown){const b=GrantSchema.parse(body);const raw=secureToken();const validFrom=new Date(),validUntil=new Date(Date.now()+b.validForHours*3600000);const row=await this.tenantDb.run(orgId,async tx=>{await tx.batteryItem.findFirstOrThrow({where:{id:b.batteryItemId,organisationId:orgId}});return tx.accessGrant.create({data:{organisationId:orgId,batteryItemId:b.batteryItemId,granteeSubject:b.granteeSubject,tokenHash:sha256Hex(raw),granteeRole:b.granteeRole,accessTier:b.accessTier,purpose:b.purpose,validFrom,validUntil,grantedBySubject:actor.subject}})});await this.audit.log({organisationId:orgId,actorSubject:actor.subject,action:'access_grant.create',resourceType:'access_grant',resourceId:row.id,metadata:{tier:b.accessTier,purpose:b.purpose}});const base=this.config.get<string>('RESTRICTED_ACCESS_BASE_URL')||'http://localhost:3000/access';return {grant:{...row,tokenHash:undefined},accessUrl:`${base}#token=${encodeURIComponent(raw)}`,securityNotice:'Capability token is shown once. Authority-only data is deliberately excluded from this token mechanism.'};}
 @Public() @Post('restricted-access/session') async session(@Headers('x-passport-access-token') token:string){const x=await this.tokens.resolve(token);const snapshot=await this.tenantDb.run(x.organisationId,tx=>tx.passportVersion.findFirst({where:{organisationId:x.organisationId,batteryItemId:x.grant.batteryItemId||undefined,publicationState:'published'},orderBy:{versionNo:'desc'}}));if(!snapshot)throw new ConflictException({code:'NO_PUBLISHED_PASSPORT'});const c:any=snapshot.canonicalJson;const allowed=new Set(fields.filter(f=>f.access_tier==='public'||f.access_tier===x.grant.accessTier).map(f=>f.id));const output={...c,values:(c.values||[]).filter((v:any)=>allowed.has(v.fieldId)),access:{tier:x.grant.accessTier,purpose:x.grant.purpose,expiresAt:x.grant.validUntil}};await this.audit.log({organisationId:x.organisationId,actorSubject:`grant:${x.grant.granteeSubject}`,action:'passport.restricted_read',resourceType:'passport_version',resourceId:snapshot.id,metadata:{tier:x.grant.accessTier,purpose:x.grant.purpose}});return output;}
}
