'use client';
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import DevAuthPanel from '../../components/DevAuthPanel';
import {apiFetch} from '../../lib/api';

type Profile={entityType:string;legalName:string;streetAddress:string;postOfficeBox?:string;extendedAddress?:string;locality?:string;postalCode?:string;region?:string;countryOfRegistration:string;identifierType:string;identifierValue:string;complianceEmail:string;compliancePhoneCountryCode:string;compliancePhone:string;legalRepresentativeFirstName:string;legalRepresentativeLastName:string;legalRepresentativeEmail:string};
const initial:Profile={entityType:'legal_person',legalName:'',streetAddress:'',countryOfRegistration:'NL',identifierType:'NTR',identifierValue:'',complianceEmail:'',compliancePhoneCountryCode:'+31',compliancePhone:'',legalRepresentativeFirstName:'',legalRepresentativeLastName:'',legalRepresentativeEmail:''};

export default function RegistryOnboarding(){
 const[p,setP]=useState<Profile>(initial);const[status,setStatus]=useState<any>();const[msg,setMsg]=useState('');
 async function load(){try{const existing=await apiFetch('/organisations/registry-profile');if(existing)setP({...initial,...existing});const r=await apiFetch('/organisations/registry-profile/readiness');setStatus(r)}catch(e:any){setMsg(e.message)}}
 useEffect(()=>{load()},[]);
 async function save(){try{setMsg('Saving…');await apiFetch('/organisations/registry-profile',{method:'POST',body:JSON.stringify(p)});setMsg('Registry enrolment profile saved.');await load()}catch(e:any){setMsg(e.message)}}
 const field=(key:keyof Profile,label:string,placeholder='')=><label><span>{label}</span><input value={(p[key]??'') as string} placeholder={placeholder} onChange={e=>setP(v=>({...v,[key]:e.target.value}))}/></label>;
 return <AppShell><section className="pageHead"><div><div className="kicker">REGISTRY ENROLMENT PREP</div><h1>Prepare the exact organisation data before EU Registry verification.</h1><p>This screen mirrors the current Commission enrolment requirements for a legal person. It does not self-certify or mark your organisation verified.</p></div></section><DevAuthPanel/>
 <div className="stepGrid"><section className="panel"><span className="stepNo">01</span><h2>Legal entity</h2>{field('legalName','Legal registered name')}{field('streetAddress','Street address')}{field('postalCode','Postal code')}{field('locality','Locality')}{field('region','Region')}{field('countryOfRegistration','Country of registration (2-letter code)')}</section>
 <section className="panel"><span className="stepNo">02</span><h2>Registry identifier</h2><label><span>Identifier type</span><select value={p.identifierType} onChange={e=>setP(v=>({...v,identifierType:e.target.value}))}><option>NTR</option><option>LEI</option><option>VAT</option><option value="EID">eID</option><option>LOCAL</option></select></label>{field('identifierValue','Identifier value')}<p className="tiny">The current Registry user guide lists NTR as preferred for legal persons.</p></section>
 <section className="panel"><span className="stepNo">03</span><h2>Compliance contact</h2>{field('complianceEmail','Compliance email')}{field('compliancePhoneCountryCode','Phone country code')}{field('compliancePhone','Phone number')}</section>
 <section className="panel"><span className="stepNo">04</span><h2>Legal representative</h2>{field('legalRepresentativeFirstName','First name')}{field('legalRepresentativeLastName','Last name')}{field('legalRepresentativeEmail','Email')}<p className="tiny">For a legal person, the EC-sealed declaration must be sealed with a qualified electronic seal from a QTSP. Certificate attributes must match the Registry data.</p></section></div>
 <section className="panel"><div className="panelTop"><div><h2>Verification readiness</h2><p>Platform-side preparation only. External EU Registry verification remains authoritative.</p></div><button className="button" onClick={save}>Save profile</button></div>{msg&&<div className="log"><div>{msg}</div></div>}<div className="metrics"><div className="metricCard"><span>Preparation</span><strong>{status?.ready?'READY':'OPEN'}</strong><small>{status?.blockers?.length??'—'} blocking conditions</small></div><div className="metricCard warn"><span>Registry identity</span><strong>{status?.registryIdentity?.status?.toUpperCase?.()||'UNVERIFIED'}</strong><small>Only actual Registry verification may change this state</small></div></div>{status?.blockers?.length?<div className="log">{status.blockers.map((x:string,i:number)=><div key={i}>BLOCKER · {x}</div>)}</div>:null}{status?.warnings?.length?<div className="log">{status.warnings.map((x:string,i:number)=><div key={i}>CHECK · {x}</div>)}</div>:null}</section></AppShell>
}
