import { translate, localeHref, type Locale } from "@/lib/i18n";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
export function PrivacyPage({ locale = "nl" }: {
    locale?: Locale;
}) {
    const t = (text: string) => translate(locale, text);
    return <><SiteHeader locale={locale}/><main id="main" className="shell content-page"><article className="legal-copy"><p className="eyebrow">{t("Jouw gegevens")}</p><h1>{t("Privacyverklaring")}</h1><p>{t("Laatst bijgewerkt: 18 september 2026.")}</p><h2>{t("Contact")}</h2><p>{"" + t("Voor vragen over de verwerking van gegevens bij EUBatteryPassport kun je contact opnemen via") + " "}<a href="mailto:info@eubatterypassport.nl">info@eubatterypassport.nl</a>.</p><h2>{t("Wat verwerken we?")}</h2><p>{t("Als je een intake indient, ontvangen we je bedrijfsnaam, e-mailadres, gekozen batterijtoepassing en de toelichting die je zelf invult. We registreren ook het moment van indienen en een aanvraagnummer.")}</p><h2>{t("Waarvoor gebruiken we deze gegevens?")}</h2><p>{t("We gebruiken deze gegevens om je vraag te beoordelen, je aanvraag te beantwoorden en op jouw verzoek mogelijke dienstverlening te bespreken. Voor deze behandeling nemen we op jouw verzoek stappen voorafgaand aan een mogelijke overeenkomst. We gebruiken intakegegevens niet automatisch voor nieuwsbrieven of reclame.")}</p><h2>{t("Opslag en beveiliging")}</h2><p>{t("De website en het intakeformulier worden gehost via OpenAI Sites en de bijbehorende Cloudflare-infrastructuur. Gegevens worden opgeslagen voor de behandeling van je aanvraag. Dienstverleners kunnen gegevens buiten de Europese Economische Ruimte verwerken; hun geldende gegevensbeschermingsafspraken zijn daarop van toepassing.")}</p><p>{t("Om misbruik van het formulier te beperken, gebruiken we tijdelijk een niet direct leesbare afgeleide van het IP-adres. Het formulier bewaart het ruwe IP-adres niet in het aanvraagdossier. De hostingdienst kan daarnaast technische toegangslogboeken verwerken.")}</p><h2>{t("Hoe lang bewaren we gegevens?")}</h2><p>{t("We bewaren intakegegevens zolang ze nodig zijn om je aanvraag af te handelen. Oude, niet meer benodigde aanvragen worden verwijderd bij het opschonen van de intakeadministratie. Als een opdracht ontstaat, gelden afzonderlijke afspraken voor het klantdossier en eventuele wettelijke bewaarplichten.")}</p><h2>{t("Je rechten")}</h2><p>{t("Je kunt vragen om inzage, correctie of verwijdering van je gegevens, of om beperking van de verwerking. Waar van toepassing kun je bezwaar maken of je gegevens opvragen in een overdraagbaar formaat. Je kunt ook een klacht indienen bij de Autoriteit Persoonsgegevens.")}</p><h2>{t("Cookies")}</h2><p>{t("Deze website plaatst geen advertentiecookies of statistiekcookies. Technische functies van de hostingdienst kunnen noodzakelijk zijn voor beveiliging en het functioneren van de website.")}</p><h2>{t("Wat hoort niet in de intake?")}</h2><p>{t("Stuur via dit formulier geen identiteitsbewijzen, wachtwoorden, vertrouwelijke technische dossiers of bijzondere persoonsgegevens. De intake is bedoeld voor een korte eerste beschrijving.")}</p></article></main><SiteFooter locale={locale}/></>;
}
