import {ArrowRight,Check,FileText,Leaf,Database,ShieldCheck,ChartNoAxesCombined,Recycle,Users,Globe2} from "lucide-react";
import {Button} from "@/components/ui/button";
import {SiteHeader} from "@/components/site-header";
import {SiteFooter} from "@/components/site-footer";
const services=[
 {Icon:Leaf,tone:"green",title:"Inzicht in de eisen",text:"Maak inzichtelijk welke gegevens bij jouw batterij horen.",detail:"We brengen je batterijtype, je rol in de keten en de benodigde informatie samen in een overzichtelijk dossier."},
 {Icon:Database,tone:"blue",title:"Gegevens en bewijs",text:"Breng productinformatie en documenten samen.",detail:"Van technische specificaties tot leveranciersinformatie: koppel gegevens aan hun bron en maak ontbrekende informatie zichtbaar."},
 {Icon:ShieldCheck,tone:"gold",title:"Opstellen en beheren",text:"Van een eerste dossier naar een actueel batterijpaspoort.",detail:"Werk vanuit een gestructureerd dossier aan het digitale paspoort. Leg vast welke informatie gecontroleerd, aangevuld of bijgewerkt moet worden."},
 {Icon:ChartNoAxesCombined,tone:"purple",title:"Overzicht in de keten",text:"Houd informatie van leveranciers en producten bij elkaar.",detail:"Maak duidelijk welke informatie van welke partij komt. Zo blijft het verband tussen product, leverancier en bewijsstuk behouden."}
];
const benefits=[{Icon:Recycle,text:"Productinformatie op één plek"},{Icon:Leaf,text:"Inzicht in gegevens en bewijs"},{Icon:Users,text:"Informatie delen in de keten"},{Icon:Globe2,text:"Gegevens actueel houden"}];
export default function Home(){return <><SiteHeader/><main id="main">
<section className="hero shell"><div className="hero-art"><img src="/images/battery-passport.webp" alt="Accu met een zichtbaar eraan hangend batterijpaspoort" width="1122" height="1402" fetchPriority="high"/></div><div className="hero-copy"><div className="eyebrow-row"><span className="outline-pill">Digitale batterijpaspoorten</span><span className="eyebrow">Van data naar overzicht</span></div><h1>Jouw batterij.<br/>Het <span className="blue-word">verhaal</span> in<br/><span className="green-word">één paspoort.</span></h1><p className="hero-intro">Van productgegevens en bewijsstukken tot het opstellen en beheren van jouw digitale batterijpaspoort.</p><div className="hero-actions"><Button asChild className="glow-button"><a href="/intake">Start online intake <ArrowRight size={22}/></a></Button><a className="example-link" href="/voorbeeld"><span><FileText size={23}/></span>Bekijk een<br/>voorbeeld</a></div><ul className="check-list">{["Gegevens en bewijsstukken samen","Ondersteuning van begin tot eind","Van batterijdata tot paspoort"].map(t=><li key={t}><Check size={16}/>{t}</li>)}</ul></div></section>
<section className="audience-strip shell" id="voor-wie" aria-label="Voor wie"><span className="eyebrow">Voor de hele<br/>batterijketen</span><span>Fabrikanten</span><span>Importeurs</span><span>Distributeurs</span></section>
<section className="service-grid shell" id="aanpak" aria-label="Onze aanpak">{services.map(({Icon,tone,title,text,detail})=><article className={"service-card "+tone} key={title}><Icon className="service-icon" strokeWidth={1.3}/><h2>{title}</h2><p>{text}</p><details><summary aria-label={"Meer over "+title}><ArrowRight size={20}/><span className="sr-only">Meer informatie</span></summary><p>{detail}</p></details></article>)}</section>
<section className="vision shell"><div className="landscape-panel"><img src="/images/alpine-valley.webp" alt="Berglandschap met een rivier door een groene vallei" width="1448" height="1086" loading="lazy"/><h2>Batterijgegevens<br/>die verder<br/>brengen.</h2><span className="eyebrow">Één paspoort.<br/>Een helder verhaal.</span></div><div className="vision-copy"><p className="eyebrow">De kracht van het<br/>batterijpaspoort</p><ul>{benefits.map(({Icon,text})=><li key={text}><Icon strokeWidth={1.5}/><span>{text}</span></li>)}</ul><p className="signature">Van inzicht<br/>naar vooruitgang</p></div></section>
<section className="value-band shell" aria-label="Wat het oplevert">{[["DATA","Productgegevens bijeen"],["BEWIJS","Documenten bij je dossier"],["INZICHT","Overzicht in ontbrekende gegevens"],["BEHEER","Een paspoort dat meegroeit"]].map(([title,text])=><div key={title}><strong>{title}</strong><p>{text}</p></div>)}</section>
<section className="closing shell"><div className="process-note"><FileText size={52} strokeWidth={1}/><div><h2>Van eerste gegevens<br/>tot digitaal paspoort.</h2><p>Verzamelen, structureren, opstellen en beheren. Een duidelijk proces voor jouw batterijgegevens.</p></div></div><div className="closing-cta"><p className="eyebrow green-word">Zet de volgende stap</p><a href="/intake"><h2>Start jouw online intake</h2><span className="circle-arrow"><ArrowRight/></span></a><p>Vertel ons over je bedrijf,<br/>je batterijen en je vraag.</p></div></section>
<section className="faq shell" id="vragen"><p className="eyebrow">Goed om te weten</p><h2>Veelgestelde vragen</h2><div>{[
["Waar begin ik als mijn gegevens nog niet compleet zijn?","Begin met wat je al hebt: het batterijtype, de toepassing en de beschikbare productinformatie. In de intake kun je ook aangeven wat nog onbekend is."],
["Gaat het alleen om het verzamelen van gegevens?","De dienstverlening omvat het traject van productgegevens en bewijsstukken tot het opstellen en beheren van digitale batterijpaspoorten. Welke onderdelen voor jouw organisatie passen, leggen we vooraf vast."],
["Is een batterijpaspoort hetzelfde als een keurmerk?","Een digitaal batterijpaspoort is een informatiedossier. Het is op zichzelf geen keurmerk of garantie dat een product aan alle toepasselijke eisen voldoet."],
["Wat gebeurt er na de intake?","We bekijken je vraag en de beschikbare informatie. Daarna bepalen we welke vervolgstappen en dienstverlening aansluiten bij jouw organisatie. De intake verplicht je tot niets."]
].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
</main><SiteFooter/></>}

